backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'post'
    label: 'Post'
    folder: 'content/post'
    media_folder: ""
    public_folder: ""
    format: 'frontmatter'
    create: true
    slug: '{{slug}}/index'
    # editor:
      # preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'image', widget: 'image' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    files:
      - files: "content/_index.md"
        label: 'Home Page'
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Welcome Message", name: "welcome", widget: "text" }
          - { label: "Book Description", name: "bookDescription", widget: "text" }
          - { 
              label: "Book Reviews", 
              name: 'bookReviews', 
              widget: "list", 
              collapsed: true, 
              summary: "{{fields.name}}",
              fields:
              - { label: "Name", name: "name", widget: string, default: "John Doe" }
              - { label: "Review", name: "review", widget: text, default: "This is a book review about Light in the Darkness" }
            }
          - { 
              label: "Instagram Posts", 
              name: 'instagram', 
              widget: "list", 
              collapsed: true, 
              summary: '{{fields.image}}',
              fields:
              - { label: "Image", name: "image", widget: image}

          }
         
      - file: "content/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "text" }