backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    media_folder: "/static/img/blog"
    public_folder: ""
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    # editor:
      # preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'image', widget: 'image' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Instagram Link', name: 'igLink', widget: 'string' ,default:''}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'books'
    label: 'Books'
    folder: 'content/books'
    media_folder: "/static/img/books"
    public_folder: ""
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    # editor:
      # preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Book Image', name: 'image', widget: 'image' }
      - { label: 'Description', name: 'description', widget: 'string' }
  - name: 'global'
    label: 'Global'
    files: 
      - file: "content/footer.md"
        label: "Footer"
        name: "footer"
        fields:
          - { label: "Footer Text", name: 'footerText', widget: 'string'}
          - { label: "Footer Form Text", name: 'formText', widget: 'string'}
          - label: "Instagram Posts" 
            name: 'instagram'
            widget: "list" 
            collapsed: true 
            summary: '{{fields.image}}'
            fields:
              - { label: "Image", name: "image", widget: image,  media_folder: '/static/img/instagram' , allow_multiple: true}
  - name: 'pages'
    label: 'Pages'
    files:
      - file: "content/pages/home.md"
        label: 'Home Page'
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Welcome Message", name: "welcome", widget: "text" }
          - { label: "Bio Short", name: "bioShort", widget: "text", default: 'This is text for the bio short. This is text for the bio short. This is text for the bio short. This is text for the bio short. '  }
          - { label: "Book Description", name: "bookDescription", widget: "text" }
          - label: "Book Reviews" 
            name: 'bookReviews' 
            widget: "list" 
            collapsed: true 
            summary: "{{fields.name}}"
            fields:
              - { label: "Name", name: "name", widget: 'string', default: "John Doe" }
              - { label: "Review", name: "review", widget: 'text', default: "This is a book review about Light in the Darkness" }
          
      - file: "content/pages/about.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "About Full", name: "aboutFull", widget: "text" }
      - file: "content/pages/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - { label: "Contact Message", name: "message", widget: "text" }